apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarqube
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
