apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDatabase.passwordSecret }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sonarqube.licenseSecret }}
type: Opaque
data:
  license.txt: {{ .Values.sonarqube.license | b64enc }}
