apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: {{ .Values.sonarqube.service.type }}
  ports:
  - port: {{ .Values.sonarqube.service.port }}
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: sonarqube
